# Generated by Django 2.2.7 on 2019-12-19 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.date.today)),
                ('content', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('FIO', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='net_of_company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='products',
        ),
        migrations.RemoveField(
            model_name='company',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Net_Of_Companies',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
