# Generated by Django 2.2.7 on 2019-12-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191219_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='url_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
