# Generated by Django 2.2.7 on 2020-01-14 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_new_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
