# Generated by Django 2.2.7 on 2020-01-14 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200114_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
