# Generated by Django 2.2.7 on 2020-01-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200114_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
