# Generated by Django 2.2.7 on 2020-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_new_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.CharField(default='<built-in method today of type object at 0x000007FEE6F03530>', max_length=300),
        ),
    ]
